name: Build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2023-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Install Roborio Toolchain
      run: ./gradlew installRoborioToolchain

    - name: Compile and run tests on robot code
      run: ./gradlew build